name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 16 * * *"}]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    
      - name: 🦑 General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          base_hireable: yes
          config_timezone: America/Buenos_Aires
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_calendar: yes
          plugin_repositories: yes
          plugin_repositories_featured: kaku, palettePilot, hyprland-dots
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_ignored: html, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot, scala, c, c++, python, ejs, css, shell
          plugin_languages_limit: 3
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_topics_sort: stars

      - name: 🦑 Medias
        uses: lowlighter/metrics@latest
        with:
          filename: medias.svg
          # Current configuration doesn't require a GitHub token
          token: NOT_NEEDED

          # Options
          base: ""
          base_hireable: yes
          config_timezone: America/Buenos_Aires
          plugin_anilist: yes
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_shuffle: yes
          plugin_anilist_user: linuxmobile
          plugin_music: yes
          plugin_music_limit: 6
          plugin_music_mode: recent
          plugin_music_played_at: yes
          plugin_music_playlist: https://open.spotify.com/embed/playlist/69gzjQcRJvfSnA1Rf8bhAK
          plugin_music_provider: spotify
          plugin_music_token: "${{ secrets.CLIENT_ID }}, ${{ secrets.CLIENT_SECRET }}, ${{ secrets.REFRESH_TOKEN }}"
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_user: elrastaok
          plugin_pagespeed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://linudev-sage.vercel.app/
